# CMake generated Testfile for 
# Source directory: /mnt/d/Projects/CLion/OS/ihw-1/test
# Build directory: /mnt/d/Projects/CLion/OS/ihw-1/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_group_0_test_0]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=0" "-N=10" "-Alpha=2")
set_tests_properties([=[test_group_0_test_0]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_0_test_1]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=1" "-N=10" "-Alpha=2")
set_tests_properties([=[test_group_0_test_1]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_0_test_2]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=2" "-N=10" "-Alpha=2")
set_tests_properties([=[test_group_0_test_2]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_0_test_3]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=3" "-N=10" "-Alpha=2")
set_tests_properties([=[test_group_0_test_3]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_0_test_4]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=4" "-N=10" "-Alpha=2")
set_tests_properties([=[test_group_0_test_4]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_0_test_5]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=5" "-N=10" "-Alpha=2")
set_tests_properties([=[test_group_0_test_5]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_0_test_6]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=6" "-N=10" "-Alpha=2")
set_tests_properties([=[test_group_0_test_6]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_0_test_7]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=7" "-N=10" "-Alpha=2")
set_tests_properties([=[test_group_0_test_7]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_0_test_8]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=8" "-N=10" "-Alpha=2")
set_tests_properties([=[test_group_0_test_8]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_0_test_9]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=9" "-N=10" "-Alpha=2")
set_tests_properties([=[test_group_0_test_9]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_1_test_0]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=10" "-N=10" "-Alpha=26")
set_tests_properties([=[test_group_1_test_0]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_1_test_1]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=11" "-N=10" "-Alpha=26")
set_tests_properties([=[test_group_1_test_1]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_1_test_2]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=12" "-N=10" "-Alpha=26")
set_tests_properties([=[test_group_1_test_2]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_1_test_3]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=13" "-N=10" "-Alpha=26")
set_tests_properties([=[test_group_1_test_3]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_1_test_4]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=14" "-N=10" "-Alpha=26")
set_tests_properties([=[test_group_1_test_4]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_1_test_5]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=15" "-N=10" "-Alpha=26")
set_tests_properties([=[test_group_1_test_5]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_1_test_6]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=16" "-N=10" "-Alpha=26")
set_tests_properties([=[test_group_1_test_6]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_1_test_7]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=17" "-N=10" "-Alpha=26")
set_tests_properties([=[test_group_1_test_7]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_1_test_8]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=18" "-N=10" "-Alpha=26")
set_tests_properties([=[test_group_1_test_8]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_1_test_9]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=19" "-N=10" "-Alpha=26")
set_tests_properties([=[test_group_1_test_9]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_2_test_0]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=20" "-N=10" "-Alpha=128")
set_tests_properties([=[test_group_2_test_0]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_2_test_1]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=21" "-N=10" "-Alpha=128")
set_tests_properties([=[test_group_2_test_1]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_2_test_2]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=22" "-N=10" "-Alpha=128")
set_tests_properties([=[test_group_2_test_2]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_2_test_3]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=23" "-N=10" "-Alpha=128")
set_tests_properties([=[test_group_2_test_3]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_2_test_4]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=24" "-N=10" "-Alpha=128")
set_tests_properties([=[test_group_2_test_4]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_2_test_5]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=25" "-N=10" "-Alpha=128")
set_tests_properties([=[test_group_2_test_5]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_2_test_6]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=26" "-N=10" "-Alpha=128")
set_tests_properties([=[test_group_2_test_6]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_2_test_7]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=27" "-N=10" "-Alpha=128")
set_tests_properties([=[test_group_2_test_7]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_2_test_8]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=28" "-N=10" "-Alpha=128")
set_tests_properties([=[test_group_2_test_8]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_2_test_9]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=29" "-N=10" "-Alpha=128")
set_tests_properties([=[test_group_2_test_9]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_3_test_0]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=30" "-N=100" "-Alpha=128")
set_tests_properties([=[test_group_3_test_0]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_3_test_1]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=31" "-N=100" "-Alpha=128")
set_tests_properties([=[test_group_3_test_1]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_3_test_2]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=32" "-N=100" "-Alpha=128")
set_tests_properties([=[test_group_3_test_2]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_3_test_3]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=33" "-N=100" "-Alpha=128")
set_tests_properties([=[test_group_3_test_3]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_3_test_4]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=34" "-N=100" "-Alpha=128")
set_tests_properties([=[test_group_3_test_4]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_3_test_5]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=35" "-N=100" "-Alpha=128")
set_tests_properties([=[test_group_3_test_5]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_3_test_6]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=36" "-N=100" "-Alpha=128")
set_tests_properties([=[test_group_3_test_6]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_3_test_7]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=37" "-N=100" "-Alpha=128")
set_tests_properties([=[test_group_3_test_7]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_3_test_8]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=38" "-N=100" "-Alpha=128")
set_tests_properties([=[test_group_3_test_8]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_3_test_9]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=39" "-N=100" "-Alpha=128")
set_tests_properties([=[test_group_3_test_9]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_4_test_0]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=40" "-N=100000" "-Alpha=128")
set_tests_properties([=[test_group_4_test_0]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_4_test_1]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=41" "-N=100000" "-Alpha=128")
set_tests_properties([=[test_group_4_test_1]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_4_test_2]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=42" "-N=100000" "-Alpha=128")
set_tests_properties([=[test_group_4_test_2]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_4_test_3]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=43" "-N=100000" "-Alpha=128")
set_tests_properties([=[test_group_4_test_3]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_4_test_4]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=44" "-N=100000" "-Alpha=128")
set_tests_properties([=[test_group_4_test_4]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_4_test_5]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=45" "-N=100000" "-Alpha=128")
set_tests_properties([=[test_group_4_test_5]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_4_test_6]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=46" "-N=100000" "-Alpha=128")
set_tests_properties([=[test_group_4_test_6]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_4_test_7]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=47" "-N=100000" "-Alpha=128")
set_tests_properties([=[test_group_4_test_7]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_4_test_8]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=48" "-N=100000" "-Alpha=128")
set_tests_properties([=[test_group_4_test_8]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
add_test([=[test_group_4_test_9]=] "/mnt/d/Projects/CLion/OS/ihw-1/test/check" "-test=49" "-N=100000" "-Alpha=128")
set_tests_properties([=[test_group_4_test_9]=] PROPERTIES  _BACKTRACE_TRIPLES "/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;16;add_test;/mnt/d/Projects/CLion/OS/ihw-1/test/CMakeLists.txt;0;")
